#!/usr/bin/env python3
"""
Script to detect missing locale files in react-phone-hooks by comparing
against locales available in antd-phone-input and mui-phone-input dependencies.
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Set, List, Dict
from urllib.request import urlopen


def get_existing_locales() -> Set[str]:
    """
    Extract locale keys from the existing locale.ts file in react-phone-hooks.
    """
    project_root = Path(__file__).parent.parent.parent
    locale_file = project_root / "src" / "locale.ts"
    
    if not locale_file.exists():
        print(f"Error: locale.ts not found at {locale_file}")
        sys.exit(1)
    
    with open(locale_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Extract all exported locale constants (e.g., "export const enUS = {")
    locale_pattern = r'^export const (\w+) = \{'
    locales = set(re.findall(locale_pattern, content, re.MULTILINE))
    
    return locales


def get_antd_locales() -> Set[str]:
    """
    Fetch available locale keys from antd package by checking the locale imports
    in the development ant-phone locale.ts file.
    """
    project_root = Path(__file__).parent.parent.parent
    ant_locale_file = project_root / "development" / "src" / "ant-phone" / "locale.ts"
    
    if not ant_locale_file.exists():
        print(f"Warning: ant-phone locale.ts not found at {ant_locale_file}")
        return set()
    
    with open(ant_locale_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Extract antd locale imports (e.g., "import enUS from "antd/es/locale/en_US";")
    import_pattern = r'^import (\w+) from "antd/es/locale/'
    locales = set(re.findall(import_pattern, content, re.MULTILINE))
    
    return locales


def get_mui_locales_from_package() -> Set[str]:
    """
    Fetch available locale keys from @mui/material package by checking
    the mui-phone locale.ts structure and inferring from MUI's locale module.
    
    Since MUI locales are accessed dynamically via "@mui/material/locale",
    we need to check what locales are available in the package.
    """
    # MUI Material has built-in locales that can be imported
    # Common MUI locales based on their documentation
    mui_locales = {
        'arEG', 'arSA', 'arSD', 'azAZ', 'bgBG', 'bnBD', 'caES', 'csCZ',
        'daDK', 'deDE', 'elGR', 'enUS', 'esES', 'etEE', 'faIR', 'fiFI',
        'frFR', 'heIL', 'hiIN', 'hrHR', 'huHU', 'hyAM', 'idID', 'isIS',
        'itIT', 'jaJP', 'khKH', 'kkKZ', 'koKR', 'ltLT', 'lvLV', 'mkMK',
        'mnMN', 'nbNO', 'nlNL', 'plPL', 'ptBR', 'ptPT', 'roRO', 'ruRU',
        'siLK', 'skSK', 'srRS', 'svSE', 'thTH', 'trTR', 'ukUA', 'urPK',
        'viVN', 'zhCN', 'zhHK', 'zhTW'
    }
    
    return mui_locales


def format_missing_locales_issue(missing_locales: Dict[str, Set[str]]) -> str:
    """
    Format the missing locales into a GitHub issue body.
    """
    if not any(missing_locales.values()):
        return ""
    
    issue_body = """## Missing Locale Translations

This automated check has detected missing locale files in `react-phone-hooks` that are available in dependent packages.

### Summary

"""
    
    total_missing = sum(len(locales) for locales in missing_locales.values())
    issue_body += f"**Total missing locales: {total_missing}**\n\n"
    
    for source, locales in missing_locales.items():
        if locales:
            issue_body += f"### Missing from {source}\n\n"
            for locale in sorted(locales):
                issue_body += f"- `{locale}`\n"
            issue_body += "\n"
    
    issue_body += """### Action Required

Please add translation entries for the missing locales listed above. Each locale should include:
- `searchNotFound`: Translation for "Country not found"
- `searchPlaceholder`: Translation for "Search country"
- `countries`: Object mapping English country names to translations

### Example Structure

```typescript
export const enUS = {
    searchNotFound: "Country not found",
    searchPlaceholder: "Search country",
    countries: {
        "United States": "United States",
        "United Kingdom": "United Kingdom",
        // ... other countries
    },
}
```

---
*This issue was automatically generated by the locale detection script.*
"""
    
    return issue_body


def main():
    """
    Main function to detect missing locales and output results.
    """
    print("Checking for missing locales in react-phone-hooks...")
    
    # Get existing locales
    existing_locales = get_existing_locales()
    print(f"Found {len(existing_locales)} existing locales in react-phone-hooks")
    
    # Get locales from dependent packages
    antd_locales = get_antd_locales()
    print(f"Found {len(antd_locales)} locales in antd")
    
    mui_locales = get_mui_locales_from_package()
    print(f"Found {len(mui_locales)} locales in MUI")
    
    # Find missing locales
    missing_from_antd = antd_locales - existing_locales
    missing_from_mui = mui_locales - existing_locales
    
    # Combine and deduplicate
    all_missing = missing_from_antd | missing_from_mui
    
    missing_locales = {}
    if missing_from_antd:
        missing_locales['antd'] = missing_from_antd
    if missing_from_mui:
        missing_locales['mui'] = missing_from_mui
    
    # Output results
    if all_missing:
        print(f"\n❌ Found {len(all_missing)} missing locale(s):")
        for locale in sorted(all_missing):
            sources = []
            if locale in missing_from_antd:
                sources.append("antd")
            if locale in missing_from_mui:
                sources.append("MUI")
            print(f"  - {locale} (from: {', '.join(sources)})")
        
        # Generate issue body
        issue_body = format_missing_locales_issue(missing_locales)
        
        # Save to file for GitHub Actions
        output_file = Path("/tmp/missing_locales_issue.md")
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(issue_body)
        
        print(f"\n📝 Issue body saved to {output_file}")
        
        # Set output for GitHub Actions
        if os.getenv('GITHUB_OUTPUT'):
            with open(os.getenv('GITHUB_OUTPUT'), 'a') as f:
                f.write(f"has_missing=true\n")
                f.write(f"count={len(all_missing)}\n")
        
        sys.exit(1)  # Exit with error to indicate missing locales
    else:
        print("\n✅ No missing locales found!")
        
        # Set output for GitHub Actions
        if os.getenv('GITHUB_OUTPUT'):
            with open(os.getenv('GITHUB_OUTPUT'), 'a') as f:
                f.write(f"has_missing=false\n")
                f.write(f"count=0\n")
        
        sys.exit(0)


if __name__ == "__main__":
    main()
