import os
import re
import subprocess
import sys
from pathlib import Path


project_root = Path(__file__).parent.parent.parent
locale_file = project_root / "src" / "locale.ts"
ant_locale_file = project_root / "development" / "src" / "ant-phone" / "locale.ts"


with open(locale_file, 'r') as f:
    content = f.read()

locale_pattern = r'^export const (\w+) = \{'
existing_locales = set(re.findall(locale_pattern, content, re.MULTILINE))

with open(ant_locale_file, 'r') as f:
    content = f.read()

import_pattern = r'^import (\w+) from "antd/es/locale/'
antd_locales = set(re.findall(import_pattern, content, re.MULTILINE))

try:
    result = subprocess.run(
        ['node', '-e', 'const locale = require("@mui/material/locale"); console.log(Object.keys(locale).join(","))'],
        cwd=project_root / "development",
        capture_output=True,
        text=True,
        timeout=10
    )
    if result.returncode == 0 and result.stdout.strip():
        mui_locales = set(result.stdout.strip().split(','))
    else:
        mui_locales = existing_locales
except:
    mui_locales = existing_locales

missing_from_antd = antd_locales - existing_locales
missing_from_mui = mui_locales - existing_locales
all_missing = missing_from_antd | missing_from_mui

if all_missing:
    issue_body = "## Missing Locale Translations\n\n"
    issue_body += "This automated check has detected missing locale files in `react-phone-hooks` that are available in dependent packages.\n\n"
    issue_body += "### Summary\n\n"
    issue_body += f"**Total missing locales: {len(all_missing)}**\n\n"
    
    missing_locales = {}
    if missing_from_antd:
        missing_locales['antd'] = missing_from_antd
    if missing_from_mui:
        missing_locales['mui'] = missing_from_mui
    
    for source, locales in missing_locales.items():
        if locales:
            issue_body += f"### Missing from {source}\n\n"
            for locale in sorted(locales):
                issue_body += f"- `{locale}`\n"
            issue_body += "\n"
    
    issue_body += "### Action Required\n\n"
    issue_body += "Please add translation entries for the missing locales listed above. Each locale should include:\n"
    issue_body += "- `searchNotFound`: Translation for \"Country not found\"\n"
    issue_body += "- `searchPlaceholder`: Translation for \"Search country\"\n"
    issue_body += "- `countries`: Object mapping English country names to translations\n\n"
    issue_body += "### Example Structure\n\n"
    issue_body += "```typescript\n"
    issue_body += "export const enUS = {\n"
    issue_body += "    searchNotFound: \"Country not found\",\n"
    issue_body += "    searchPlaceholder: \"Search country\",\n"
    issue_body += "    countries: {\n"
    issue_body += "        \"United States\": \"United States\",\n"
    issue_body += "        \"United Kingdom\": \"United Kingdom\",\n"
    issue_body += "    },\n"
    issue_body += "}\n"
    issue_body += "```\n\n"
    issue_body += "---\n"
    issue_body += "*This issue was automatically generated by the locale detection script.*\n"
    
    output_file = Path("/tmp/missing_locales_issue.md")
    with open(output_file, 'w') as f:
        f.write(issue_body)
    
    if os.getenv('GITHUB_OUTPUT'):
        with open(os.getenv('GITHUB_OUTPUT'), 'a') as f:
            f.write(f"has_missing=true\n")
            f.write(f"count={len(all_missing)}\n")
    
    sys.exit(1)
else:
    if os.getenv('GITHUB_OUTPUT'):
        with open(os.getenv('GITHUB_OUTPUT'), 'a') as f:
            f.write(f"has_missing=false\n")
            f.write(f"count=0\n")
    
    sys.exit(0)
